name: Install the MagAO-X software
on:
  push:
      branches:
          - 'test'
  schedule:
      - cron: '43 5 * * *'
jobs:
  install-rocky:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9-ubi-init
      env:
        MAGAOX_ROLE: ci
    steps:
      - name: Install git for checkout action
        run: 'dnf install -y git'
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: /opt/MagAOX/
          key: rocky-9-dependencies-cache-v1-${{ hashFiles('setup/*', 'setup/**/*') }}
      - run: 'bash -x setup/steps/install_rocky_9.2_packages.sh'
        name: Install OS dependencies
      - run: 'bash -lx setup/provision.sh'
        name: Auto-provision
      - run: 'bash -l setup/steps/install_MagAOX.sh'
        name: Install MagAO-X
      - run: 'make test'
        name: Run tests
        working-directory: /opt/MagAOX/source/MagAOX
  install-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      env:
        MAGAOX_ROLE: ci
        NEEDRESTART_SUSPEND: 'yes'
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: /opt/MagAOX/
          key: ubuntu-22.04-dependencies-cache-v1-${{ hashFiles('setup/*', 'setup/**/*') }}
      - run: 'bash -x setup/steps/install_ubuntu_22.04_packages.sh'
        name: Install OS dependencies
      - run: 'bash -lx setup/provision.sh'
        name: Auto-provision
      - run: 'bash -l setup/steps/install_MagAOX.sh'
        name: Install MagAO-X
      - run: 'make test'
        name: Run tests
        working-directory: /opt/MagAOX/source/MagAOX
