name: Install the MagAO-X software on Rocky Linux 9
on:
  push:
      branches:
          - 'test'
  schedule:
      - cron: '43 5 * * *'
jobs:
  install-rocky:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9-ubi-init
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache dependencies 
        uses: actions/cache@v3
        with:
          path: /opt/MagAOX/
          key: ${{ job.container.image }}-dependencies-cache-v1-${{ hashFiles('setup/*', 'setup/**/*') }}
      - run: 'bash -x setup/steps/install_rocky_9.2_packages.sh'
        name: Install OS dependencies
      - run: 'bash -lx setup/provision.sh'
        name: Auto-provision
      - run: 'bash -l setup/steps/install_MagAOX.sh ci'
        name: Install MagAO-X
      - run: 'make test'
        name: Run tests
        working-directory: /opt/MagAOX/source/MagAOX
